# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_item', '0002_auto_20170422_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='mode',
            field=models.CharField(choices=[('private', 'Private'), ('read', 'Allow read to everyone'), ('full_access', 'Allow full access to everyone')], default='full_access', max_length=20),
        ),
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
