# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_item', '0004_favorite_watch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('user', 'todo_list')]),
        ),
        migrations.AlterUniqueTogether(
            name='watch',
            unique_together=set([('user', 'todo_list')]),
        ),
    ]
