# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0005_auto_20170508_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
